export const SUBSCRIPTION_UPDATE_ADDRESS_REQUEST =
  'SUBSCRIPTION_UPDATE_ADDRESS_REQUEST'
export const SUBSCRIPTION_UPDATE_ADDRESS_SUCCESS =
  'SUBSCRIPTION_UPDATE_ADDRESS_SUCCESS'
export const SUBSCRIPTION_UPDATE_ADDRESS_FAIL =
  'SUBSCRIPTION_UPDATE_ADDRESS_FAIL'

export const SUBSCRIPTION_UPDATE_PREFRENCES_REQUEST =
  'SUBSCRIPTION_UPDATE_PREFRENCES_REQUEST'
export const SUBSCRIPTION_UPDATE_PREFRENCES_SUCCESS =
  'SUBSCRIPTION_UPDATE_PREFRENCES_SUCCESS'
export const SUBSCRIPTION_UPDATE_PREFRENCES_FAIL =
  'SUBSCRIPTION_UPDATE_PREFRENCES_FAIL'
export const SUBSCRIPTION_UPDATE_PREFRENCES_CLEAR =
  'SUBSCRIPTION_UPDATE_PREFRENCES_CLEAR'

export const SUBSCRIPTION_CANCEL_REQUEST = 'SUBSCRIPTION_CANCEL_REQUEST'
export const SUBSCRIPTION_CANCEL_SUCCESS = 'SUBSCRIPTION_CANCEL_SUCCESS'
export const SUBSCRIPTION_CANCEL_FAIL = 'SUBSCRIPTION_CANCEL_FAIL'
